# Generated by Django 3.0.2 on 2020-03-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
    ]
