# Generated by Django 3.0.2 on 2020-03-04 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField()),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='total',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='account_holder',
            field=models.CharField(default='Jane Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='billproduct',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ci',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ci',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='closing_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='local',
            name='opening_time',
            field=models.TimeField(default='9:00'),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='month',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthemployee',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='elaboration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='point_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
