# Generated by Django 3.0.2 on 2020-03-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200304_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_holder',
            field=models.CharField(blank=True, default='Jane Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_n',
            field=models.BigIntegerField(blank=True),
        ),
    ]
