# Generated by Django 3.0.2 on 2020-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200304_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_holder',
            field=models.CharField(blank=True, default='Jane Doe', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_n',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
