# Generated by Django 3.0.2 on 2020-03-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200301_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchange',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
