# Generated by Django 3.0.2 on 2020-03-01 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200301_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='elaboration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
