# Generated by Django 3.0.2 on 2020-03-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200301_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='billproduct',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='local',
            name='closing_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='local',
            name='opening_time',
            field=models.TimeField(default='9:00'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
